"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import {
  Box,
  ThemeProvider,
  createTheme,
  Typography,
  Stack,
} from "@mui/material";
import { lime } from "@mui/material/colors";
import { useRouter } from "next/navigation";
import logo from "../Graphics/Logo2.png";
import Image from "next/image";
//import { Poppins, Arimo } from "next/font/google";
//import {  Arimo } from "next/font/google";

// const poppinsFont = Poppins({
//   weight: "700",
//   subsets: ["latin"],
//   variable: "--font-poppins",
// });

// const arimoFont = Arimo({
//   weight: "700",
//   subsets: ["hebrew"],
//   variable: "--font-arimo",
// });

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const theme = createTheme({
  palette: {
    primary: {
      main: "#426872", //#a1c26d   #426872
    },
    secondary: {
      main: lime[200],
    },
    xColor: {
      main: "#FF2108",
    },
  },
  spacing: [0, 2, 4, 8, 16, 18, 22, 26, 28, 32, 60],
  typography: {
    fontFamily: "'Oswald'",
  },
});

export default function RootLayout({ children }) {
  const router = useRouter();
  const onClick = () => {
    router.push("/MyPage");
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <Stack
            direction={"row"}
            justifyContent={"center"}
            alignItems={"center"}
            gap={4}
          >
            <Image alt="logo" placeholder="logo" src={logo} width={70} />
            <Typography variant="h4">מישלוחמד</Typography>
          </Stack>

          <Box>{children}</Box>
        </ThemeProvider>
      </body>
    </html>
  );
}
