"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { Wrapper } from "./theme";
import SharedLogo from "@/Components/sharedLogo/page";
import { PageContainer } from "@/Components/shared/Shared";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PageContainer>
          <SharedLogo />
          {children}
        </PageContainer>
      </body>
    </html>
  );
}
